name: Lint
on:
  push:
  pull_request:
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Lint
        uses: golangci/golangci-lint-action@v8
